<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '271cb6f21c9ae69ccbad5cc1b8d6707c' => $vendorDir . '/wapmorgan/morphos/src/English/functions.php',
    '34d31f2fd925dfe2696a521f5ec12db2' => $vendorDir . '/wapmorgan/morphos/src/Russian/functions.php',
    '9f42032f40ad305aa09829c3c1f0768d' => $vendorDir . '/wapmorgan/morphos/src/initialization.php',
);
