CREATE TABLE comepay_payment
(
	BILL_ID		INT(11)		NOT NULL AUTO_INCREMENT,
	ORDER_ID		INT(11)		NOT NULL,
	ITERATOR		INT(11)  NOT NULL,
	PAY		INT(1)	NOT	NULL,
	CREATED		INT(1)	NOT	NULL DEFAULT '0',
	CANCELED		INT(1)	NOT	NULL DEFAULT '0',
	SUM DECIMAL(10,2) NOT NULL,
	INDEX (ORDER_ID),
	PRIMARY KEY (BILL_ID)
);
